### ISSUE TITLE
Full stack - Follow manga

### ISSUE THREAD

**Issue by D34DPlayer** [MonochromeCMS/Monochrome#39]

**Comment by D34DPlayer** [comment]
Schema:
```yaml
ChapterFollow:
  chapterId: UUID
  userId: UUID
  follows: boolean

  get: (userId, userId) => cls
  fromUser: (userId) => cls[]
  chapterFollows: (userId) => pagination chapters
```
